# Generated by Django 4.2.7 on 2026-03-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_candidate_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('checker', 'Checker'), ('employee', 'Employee'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
    ]
