# Generated by Django 4.2.7 on 2026-04-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='emp_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
