# Generated by Django 4.2.7 on 2026-04-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_candidate_emp_id_employee_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='emp_id',
            new_name='employee_id',
        ),
    ]
