# Generated by Django 4.2.7 on 2026-04-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_employee_address_line1_employee_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='app1.employee'),
        ),
        migrations.AlterField(
            model_name='education',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='app1.candidate'),
        ),
    ]
