# Generated by Django 4.2.7 on 2026-04-10 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('checker', 'Checker'), ('employee', 'Employee'), ('admin', 'Admin'), ('management', 'Management')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='employee_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app1.employee')),
            ],
        ),
    ]
